### ISSUE TITLE
Running trained FusorSV model on new samples

### ISSUE THREAD

**Issue by lslochov** [timothyjamesbecker/FusorSV#10]
Hi Tim, I've used FusorSV to train a model with one set of samples, then did a second run where I used a second set of samples, but used the model file trained on the first set. So far, FusorSV hasn't been producing merged VCFs in the "vcf" output folder (S-1.vcf files). Is this the normal behavior of FusorSV, or am I doing something wrong?

**Comment by timothyjamesbecker** [comment]
You should get output for your new samples in most cases unless the analysis runs were very different such as training on 200X coverage and then applying on very low 2X coverage.  Could you provide the command line you are using to process the new set of samples?
