### ISSUE TITLE
Example VCF files and docker FusorSV instruction for GRCh38 reference

### ISSUE THREAD

**Issue by MaestSi** [timothyjamesbecker/FusorSV#13]
Dear timothyjamesbecker,
I would like to ask if it might be possible to have a set of VCF files obtained running SV discovery tools on bam files that have Homo_sapiens_assembly38.fasta as a reference, and a docker command for running FusorSV, similarly to files in metacaller_RC1 and the docker command reported in the README file.
Thanks,
Simone

**Comment by timothyjamesbecker** [comment]
Currently there does not exist an appropriate sample call set like the one provided in metacaller_RC1.  The bam files used were taken from the 1000 genomes phase 3 publication which used the same reference and there was a published VCF call set that was used to generate the FusorSV model which we call the true call set our the paper.  There will be some effort in a future version to include results from the ongoing 1000 genomes work that uses the Hg38 reference in which case you will achieve similar accuracy.
