### ISSUE TITLE
Error when running test data

### ISSUE THREAD

**Issue by lh12565** [timothyjamesbecker/FusorSV#14]
Hi,
when I run test data, there is a error as below:

```bash
no contig directory specified
processing samples ['/data1/lh/project/sve/tim/fusion/meta_caller_RC1/HG00096', '/data1/lh/project/sve/tim/fusion/meta_caller_RC1/HG00268', '/data1/lh/project/sve/tim/fusion/meta_caller_RC1/HG00419', '/data1/lh/project/sve/tim/fusion/meta_caller_RC1/HG00759', 
......
 for chroms ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
Traceback (most recent call last):
  File "/home/lh/anaconda2/bin/FusorSV.py", line 375, in <module>
    R += ru.get_mask_regions(out_dir+'/meta/'+sv_mask_json,O)               #svmask from ref complexity
  File "/home/lh/anaconda2/lib/python2.7/site-packages/fusorsv/read_utils.py", line 140, in get_mask_regions
    N += [[np.uint32(O[k])+np.uint32(M[k][i][0]),np.uint32(O[k])+np.uint32(M[k][i][1])]] #apply offsets
KeyError: u'GL000193.1'
```

My command:
```bash
python ~/anaconda2/bin/FusorSV.py -r /data1/ref/hg19/GATK_bundle/ucsc.hg19.fasta -m /home/lh/anaconda2/lib/python2.7/site-packages/fusorsv/data/human_g1k_v37_decoy_exclude.bed -i /data1/lh/project/sve/tim/fusion/meta_caller_RC1/ -f DEFAULT -o /data1/lh/project/sve/tim/fusion/out/ -M 0.5 -L DEFAULT  -p 10
```
The "human_g1k_v37_decoy_exclude.bed" file comes from "https://github.com/timothyjamesbecker/FusorSV/releases/download/0.1.1-beta/human_g1k_v37_decoy_exclude.bed".

Thanks!

**Comment by timothyjamesbecker** [comment]
You are using hg19 in your command and not human_g1k_v37_decoy which is being used in the default SV mask human_g1k_v37_decoy_exclude.bed.  The human_g1k_v37_decoy reference has more contigs  than hg19 such as GL000193.1 and your error is a result of not using the same reference. In short you start analysis by aligning your reads to one ref and than you stick with that ref for SV calling and then again stick with that ref for FusorSV.  If you change the ref between alignment, SV calling and FusorSv steps issues can arise.

human_g1k_v37_decoy.fa can be found by reading the 1000 genomes article: http://www.internationalgenome.org/category/assembly

**Comment by lh12565** [comment]
Hi,
I changed the reference file to "human_g1k_v37.fasta"(http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz), but It still reported errors:
```bash
Traceback (most recent call last):
  File "/home/lh/anaconda2/bin/FusorSV.py", line 375, in <module>
    R += ru.get_mask_regions(out_dir+'/meta/'+sv_mask_json,O)               #svmask from ref complexity
  File "/home/lh/anaconda2/lib/python2.7/site-packages/fusorsv/read_utils.py", line 140, in get_mask_regions
    N += [[np.uint32(O[k])+np.uint32(M[k][i][0]),np.uint32(O[k])+np.uint32(M[k][i][1])]] #apply offsets
KeyError: u'NC_007605'
```
Then I replace "human_g1k_v37_decoy_exclude.bed" to "human_g1k_v37_decoy_svmask.json" and it works, but the output file is empty with headers. 

My command:
```bash
python ~/anaconda2/bin/FusorSV.py -r /data1/lh/ref/genome1000/human_g1k_v37.fasta -m /home/lh/anaconda2/lib/python2.7/site-packages/fusorsv/data/human_g1k_v37_decoy_svmask.json -i /data1/lh/project/sve/tim/fusion/meta_caller_RC1/ -f ~/anaconda2/lib/python2.7/site-packages/fusorsv/data/models/human_g1k_v37_decoy.P3.pickle.gz -o /data1/lh/project/sve/tim/fusion/timsve/ -M 0.5 -L DEFAULT  -p 10
```

Thanks!

**Comment by timothyjamesbecker** [comment]
The reference human_g1k_v37.fasta is not the same as the human_g1k_v37_decoy.fa which has extra contigs. Again you want to locate human_g1k_v37_decoy.fasta on the 1000 genomes site and use that one for the -r argument.
