### ISSUE TITLE
Empty merged vcf files with only headers.

### ISSUE THREAD

**Issue by TendoLiu** [timothyjamesbecker/FusorSV#16]
I was using human_g1k_v37_decoy.fasta consistently, and no error reported in the log file. But the output vcf were always empty header. Any idea to fix this?
#######script
fusorsvPath=/bgfs/soesterreich/pan_data/soesterreich/Tendo/InstalledTools/FusorSV/fusorsv-0.1.0.img
hg19_fasta=/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/module/RefenceFiles/hg19/ucsc.hg19.fasta
b37_fasta=/bgfs/soesterreich/pan_data/soesterreich/Tendo/ReferenceFiles/hg19_Versions/b37/human_g1k_v37.fasta
b37_decoy_fasta=/bgfs/soesterreich/pan_data/soesterreich/Tendo/ReferenceFiles/hg19_Versions/b37/human_g1k_v37_decoy.fasta

vcf=/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVE/
vcfOut=/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVEout/
maskFile=/bgfs/soesterreich/pan_data/soesterreich/Tendo/InstalledTools/FusorSV/data/fusorsv-0.1.2/fusorsv/data/human_g1k_v37_decoy_exclude.bed

FusorSV.py \
-r $b37_decoy_fasta \
-m $maskFile \
-i $vcf \
-f DEFAULT \
-o $vcfOut \
-M 0.5 \
-p 4

###output file list
![image](https://user-images.githubusercontent.com/54043441/66506661-c7893800-ea9b-11e9-967a-b9a361ce7b3c.png)

###Log
> no contig directory specified
processing samples ['/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVE/Lee_3_S3_R_S35.vcf', '/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVE/Lee_3_S3_R_S18.vcf', '/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVE/Lee_3_S3_R_S11.vcf', '/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVE/Lee_3_S3_R_S4.vcf', '/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVE/Lee_3_S3_R_S10.vcf', '/bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVE/Lee_3_S3_R_S9.vcf']
 for chroms ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
merging the svmask regions
svmask regions merged in 0.04 sec
reading, parsing, partitioning and writing sample VCFs
reading sample Lee_3_S3_R_S11.vcf
reading sample Lee_3_S3_R_S4.vcf
reading sample Lee_3_S3_R_S18.vcf
reading sample Lee_3_S3_R_S9.vcf
reading sample Lee_3_S3_R_S35.vcf
reading sample Lee_3_S3_R_S10.vcf
finished reading 6 out of 6 samples generating 0 partitions in 1.59 sec
apply fusion model to sample inputs and generating fusorSV ouput
starting fusorSV discovery on sample Lee_3_S3_R_S18.vcf
starting fusorSV discovery on sample Lee_3_S3_R_S4.vcf
starting fusorSV discovery on sample Lee_3_S3_R_S10.vcf
starting fusorSV discovery on sample Lee_3_S3_R_S35.vcf
starting fusorSV discovery on sample Lee_3_S3_R_S11.vcf
starting fusorSV discovery on sample Lee_3_S3_R_S9.vcf
finished reading samples in 315.31 sec
cluster merging tool processing samples
completed = True
run 0 in 480.66 sec

Thanks.

**Comment by qihuizhu** [comment]
Thanks for your question. We're looking into this and will get back to you

**Comment by timothyjamesbecker** [comment]
Thank you for including your command line outputs.  The FusorSV.py script is looking for a folder of sample folders each of which contain the individual VCF files.  When you wish to call a single sample, this requires that you add an additional sample folder to house your VCF files.  Make a new directory inside: mkdir /bgfs/soesterreich/pan_data/soesterreich/Tendo/Projects/Project2_cfDNA_fusion_capture/Jobtest/SVE/sample_name_here and then your existing scripts will run correctly causing FusorSV.py script to output: 
reading sample sample_name_here

I have updated the readme section that details an example for using the -i, please take a look there as well.
