### ISSUE TITLE
Questions about FusorSV

### ISSUE THREAD

**Issue by no7ren** [timothyjamesbecker/FusorSV#2]
Hi,

I think FusorSV is quite nice/powerful tool for the SV integration. I had two questions about the tool:
1. is it only for human data
2. how can I use the result of other callers (like Manta, cortex_var etc..)? can you pinpoint the direction or give an example(even better)?

Thank you!
Lik

**Comment by timothyjamesbecker** [comment]
1. It is intended for human data but should work when in other well established genomes. Generally you need a good quality call set on the genome in question.
2. You can add any caller you would like, but you then need to retrain using a known call set as was done in the paper.  You need to then prepare a new caller id map which simply is a number for each caller name and then start the program using a training set which will produce a new model file.  Then you can apply that model to new data callsets.  More detailed documentation is forthcoming!
