### ISSUE TITLE
Training model for nonhuman species 

### ISSUE THREAD

**Issue by skharrison** [timothyjamesbecker/FusorSV#20]
Hello, I have VCF files for all my samples for lumpy,delly,pindel,breakdancer, and hydra. I tried running the fusorSV script without the -f option. When doing so the output gave me a .pickle.gz file in the model directory. I tried then running it again using this as the -f option. I ended up with generated vcfs for all samples in the vcf folder, but all were empty? I am not sure how exactly I am supposed to train it properly. I cannot tell if it is this that is messing up or something else. I ended up running it with the following command the second time. No error messages just nothing but the VCF headers in each output vcf file. 

docker run -v ~/data:/data -it timothyjamesbecker/fusorsv \
FusorSV.py \
-r /data/ref/246_burkref.fa \
-c NZ_CP020397.1,NZ_CP020398.1,NZ_CP020399.1 \
-i /data/vcfs/ \
-f /data/fused_try1/models/file.pickle.gz \
-o /data/fused_result/ \
-M 0.5 \
-p 4

Any help would be appreciated!! thank you!

**Comment by timothyjamesbecker** [comment]
Can you list your sample directory (the -i /data/vcfs/ folder)?  Can you share some of the standard output from the training phase? Can you share some of the standard output from this application of your fusion model. Please feel free to look through the three points of interest mentioned and share some or all of it in order to see what is happening with your fusion model (file.pickle.gz).

**Comment by skharrison** [comment]
Thank you for getting back to me! My vcfs directory looks like this:
vcfs/sample1:
sample1_S10.vcf	sample1_S11.vcf	sample1_S17.vcf	sample1_S18.vcf	sample1_S4.vcf

vcfs/sample2:
sample2_S10.vcf	sample2_S11.vcf	sample2_S17.vcf	sample2_S18.vcf	sample2_S4.vcf

vcfs/sample3:
sample3_S10.vcf	sample3_S11.vcf	sample3_S17.vcf	sample3_S18.vcf	sample3_S4.vcf

I am definitely doing something wrong in the training phase and I am not sure how I am supposed to do it for non-human organism? I just ran it twice on the same data and used the .pickle.gz that was output from the model/ directory when I ran it the first time. I realize this was not the right thing to do because a S0.vcf is supposed to be present for while in training mode, and that is likely why I am not getting proper output. How is one supposed to generate this S0.vcf to properly train for bacterial data? Sorry I am very confused.

**Comment by timothyjamesbecker** [comment]
I see your issue now.  FusorSV is a supervised machine learning framework in which the supervision is given by a set of true VCF files.  In the case of a new species that has very different read alignment mapping statistics than the human dataset we used in the paper, you would need to have access to those true VCF files (samplename_S0.vcf).  How exactly to generate those given a very novel species can be complex, but one option that could be explored is via simulation such as Varsim. After providing some VCF calls to it Varsim will make the fastq files which you align and then run the callers on.  Varsim will generate the vcf output that you can then feed to FusorSV and this will learn the best combinations of callers to use to obtain the DEL, DUP and INV calls in your species.
