### ISSUE TITLE
Summary statistics when using an existing fusion model

### ISSUE THREAD

**Issue by kyleLesack** [timothyjamesbecker/FusorSV#21]
Hello,

I have generated a few fusion models with FusorSV that I would like to benchmark on an independent testing dataset. I am able to run FusorSV with the models generated from my training data without errors. It produces the S-1.vcf files in the vcf directory, however, the visual directory is empty except for an empty bed directory. My input directory does contain the S0.vcf truth files. When I run the same commands with FusorSV, without providing a training model, it does produce the callers_tbj , sim_matrix, and cross_fold_stats tsv files. 

Is this the expected behaviour and is there a way to have FusorSV output the performance statistics when using an existing fusion model? I can write a script to parse the S-1.vcf files, but it would save me some time if this is something that FusorSV can do.

Thanks in advance!

**Comment by timothyjamesbecker** [comment]
There is scoring functionality built within functions but no off the shelf
command line driven script to do what you want.  You would have to have the
FusorSV sources on your system and then import them as a model in order to
use the scoring functions.

Best,

-Tim

**Comment by kyleLesack** [comment]
Thanks for the response. I ended up using Bedtools to calculate those statistics.
