### ISSUE TITLE
FusorSV for SV from long-read data

### ISSUE THREAD

**Issue by WeiYang-BAI** [timothyjamesbecker/FusorSV#24]
Not an issue, I'm just wondering if FuorSV is suitable for SVs from long-read data, for example, mergeing SV callsets ( in .vcf) from different long-read/assembly-based SV callers. Thank a lot!

**Comment by timothyjamesbecker** [comment]
Not at this time, since more work is needed to understand the behavior of
the assemblies in relation to normally mapped reads.  This is an area I am
working on though.  Do you have any particular callers in mind for this?

Best,

-Tim

**Comment by WeiYang-BAI** [comment]
Thanks for the reply. 

Yes, like dipcall (https://github.com/lh3/dipcall), svim-asm (https://github.com/eldariont/svim-asm) and PAV (https://github.com/EichlerLab/pav), they are all assembly-based and haplotype-resovled methods for SV calling.
