### ISSUE TITLE
Fusion model output skips duplications/insertions

### ISSUE THREAD

**Issue by mpj5142** [timothyjamesbecker/FusorSV#25]
Hello!

I am currently using SVE and FusorSV on a cohort of ~40 individuals with WGS data. For some reason, the FusorSV output only shows DELs and INVs in the final VCF files (both per-sample and the merged all-samples file), but skips the DUPs, INS, etc. that are present in the input VCFs. 

Below is the pipeline that I am running for these samples. I am using the latest SVE docker image (with a few modifications within the image to make some of the pipelines work, for instance making bgzip exectuable for BreakSeq inputs) to generate the input VCFs (using 5 callers I was able to get working: Breakdancer, Lumpy, CNVNator, cnMOPS, and Delly). I am then running FusorSV using the latest Docker image, including using the default training model and the sv_mask file. (All data were aligned to hg19 in the first SVE step). I also ran the FusorSV step on the example data provided within the package (using the 5 callers I am using in our dataset), but its outputs appeared OK.

Do you have any experience with why the duplications/insertions might be missing? I couldn't see anything obvious from looking at the code.

Thanks!

````
singularity exec --bind /sv_ref/:/ref \
       /sv_callers/sve.sif /software/SVE/scripts/prepare_ref.py \
       -r /ref/human_g1k_v37_decoy.fa \
       -t breakseq:/data/breakseq2*.fna \
       -o /ref/sve_ref/

singularity exec --bind /sv_ref/:/ref --bind /Genotypes/WGS:/data \
       /sv_callers/sve_2.sif /software/SVE/scripts/prepare_bam.py \
       -r /ref/sve_ref/human_g1k_v37_decoy.fa \
       -f /data/$SAMPLE_R1.fastq.gz,/data/$SAMPLE_R2_001.fastq.gz \
       -o /data/sve_bams/ \
       -P 4 \
       -T 6 \
       -M 4 \
       -a speed_seq

singularity exec --bind /sv_ref/:/ref --bind /Genotypes/WGS:/data \
       /sv_callers/sve_2.sif /software/SVE/scripts/variant_processor.py \
       -r /ref/sve_ref/human_g1k_v37_decoy.fa \
       -b /data/sve_bams/$SAMPLE.bam \
       -o /data/sve_vcfs/ \
       -s breakdancer

singularity exec --bind /sv_ref/:/ref --bind /Genotypes/WGS:/data \
        /sv_callers/sve_2.sif /software/SVE/scripts/variant_processor.py \
       -r /ref/sve_ref/human_g1k_v37_decoy.fa \
       -b /data/sve_bams/$SAMPLE.bam \
       -o /data/sve_vcfs/ \
       -s lumpy

singularity exec --bind /sv_ref/:/ref --bind /Genotypes/WGS:/data \
        /sv_callers/sve_2.sif /software/SVE/scripts/variant_processor.py \
       -r /ref/sve_ref/human_g1k_v37_decoy.fa \
       -b /data/sve_bams/$SAMPLE.bam \
       -o /data/sve_vcfs/ \
       -s cnvnator

singularity exec --bind /sv_ref/:/ref --bind /Genotypes/WGS:/data \
        /sv_callers/sve_2.sif /software/SVE/scripts/variant_processor.py \
       -r /ref/sve_ref/human_g1k_v37_decoy.fa \
       -b /data/sve_bams/$SAMPLE.bam \
       -o /data/sve_vcfs/ \
       -s cnmops

singularity exec --bind /sv_ref/:/ref --bind /Genotypes/WGS:/data \
        /sv_callers/sve_2.sif /software/SVE/scripts/variant_processor.py \
       -r /ref/sve_ref/human_g1k_v37_decoy.fa \
       -b /data/sve_bams/$SAMPLE.bam \
       -o /data/sve_vcfs/ \
       -s delly

singularity exec --bind /sv_ref/:/ref --bind /Genotypes/WGS:/data \
       /sv_callers/fusorsv.sif FusorSV.py \
       -r /ref/sve_ref/human_g1k_v37_decoy.fa \
       -c 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y \
       -i /data/sve_vcfs/ \
       -o /data/sve_fused/ \
       -f DEFAULT \
       -p 1 \
       -M 0.5 \
       -L DEFAULT \
       -m /ref/human_g1k_v37_decoy_exclude.bed
````

**Comment by timothyjamesbecker** [comment]
It is possible to have very few DUP calls and of course they could be made by a less reliable caller such as BreadDancer which will make many DUP calls that are false positives that will be filtered out.  We would need to look at your input VCF files to see what is going on.  The INS types are not included in the default model since originally they were not part of the 1000 genomes phase three study VCF files that were published.  Determining INS types in short pair-end illumina data is problematic at best and will have the greatest chance of success when used with a denovo type assembly which makes it different enough as a process to perform separately. Please follow up if you can by finding a way to share some of the VCF input files so we can recreate the issue you are having.
