### ISSUE TITLE
human_g1k_v37_decoy.fa Missing

### ISSUE THREAD

**Issue by 543090lee** [timothyjamesbecker/FusorSV#26]
Hello,
I pulled a docker image from the Github, and the data folder was empty, so I am downloading the files manually.
I couldn't find human_g1k_v37_decoy.fa on the github website. Where can I download this file?

Thank you

**Comment by timothyjamesbecker** [comment]
This is not an issue related to this repo it seems you have an issue with the SVE framework that uses that fasta file along with the 1000 Genomes High coverage BAM files. The current version of FusorSV works on any fasta input.
