### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by 543090lee** [timothyjamesbecker/FusorSV#27]
Hello,
I ran the given test files and got this error,
root@11ea0a0c0cb3:/data# FusorSV.py  -r /data/human_g1k_v37.fasta  -m /data/human_g1k_v37_decoy_exclude.bed  -i /data/meta_caller_RC1/  -f DEFAULT  -o /data/meta_caller_RC1_result/  -M 0.5  -L DEFAULT  -p 4
no contig directory specified
processing samples ['/data/meta_caller_RC1/HG00096', '/data/meta_caller_RC1/HG00268', '/data/meta_caller_RC1/HG00419', '/data/meta_caller_RC1/HG00759', '/data/meta_caller_RC1/HG01051', '/data/meta_caller_RC1/HG01112', '/data/meta_caller_RC1/HG01500', '/data/meta_caller_RC1/HG01565', '/data/meta_caller_RC1/HG01583', '/data/meta_caller_RC1/HG01595', '/data/meta_caller_RC1/HG01879', '/data/meta_caller_RC1/HG02568', '/data/meta_caller_RC1/HG02922', '/data/meta_caller_RC1/HG03006', '/data/meta_caller_RC1/HG03052', '/data/meta_caller_RC1/HG03642', '/data/meta_caller_RC1/HG03742', '/data/meta_caller_RC1/NA12878', '/data/meta_caller_RC1/NA18525', '/data/meta_caller_RC1/NA18939', '/data/meta_caller_RC1/NA19017', '/data/meta_caller_RC1/NA19238', '/data/meta_caller_RC1/NA19239', '/data/meta_caller_RC1/NA19625', '/data/meta_caller_RC1/NA19648', '/data/meta_caller_RC1/NA20502', '/data/meta_caller_RC1/NA20845']
 for chroms ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
Traceback (most recent call last):
  File "/usr/local/bin/FusorSV.py", line 383, in <module>
    R += ru.get_mask_regions(out_dir+'/meta/'+sv_mask_json,O)               #svmask from ref complexity
  File "/usr/local/lib/python2.7/dist-packages/fusorsv/read_utils.py", line 149, in get_mask_regions
    N += [[np.uint32(O[k])+np.uint32(M[k][i][0]),np.uint32(O[k])+np.uint32(M[k][i][1])]] #apply offsets
KeyError: u'NC_007605'

Thank you

**Comment by timothyjamesbecker** [comment]
You should check your fasta file by using a tool like GATK/picard tools.  It looks like your fasta file does not have some sequences like the error shows: NV_007605 which is in the mask file but not in your fasta file.  This error is telling you your fasta file is lacking this sequence.  This is not a run error but a user/error with the wrong file.  Once you have the correct human_g1k_v37_decoy.fasta that matches the human_g1k_v37_decoy_exclude.bed this will run properly.
