### ISSUE TITLE
Empty VCF Files

### ISSUE THREAD

**Issue by 543090lee** [timothyjamesbecker/FusorSV#28]
Hello, 
I ran the given test files in the GitHub, and successfully got the result folders. However, the VCF folders are empty.

This is the command I ran,
root@93eb9646f494:/# FusorSV.py  -r /data/human_g1k_v37_decoy.fasta  -m /data/human_g1k_v37_decoy_exclude.bed  -i /data/meta_caller_RC1  -f DEFAULT  -o /data/meta_caller_RC1_result  -M 0.5  -L DEFAULT  -p 2
no contig directory specified
processing samples ['/data/meta_caller_RC1', '/data/meta_caller_RC1_result']
 for chroms ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
making a new coordinate offset json file
merging the svmask regions
svmask regions merged in 0.02 sec
reading, parsing, partitioning and writing sample VCFs
reading sample meta_caller_RC1
reading sample meta_caller_RC1_result
not _S*.vcf named...
finished reading 1 out of 2 samples generating 0 partitions in 0.52 sec
apply fusion model to sample inputs and generating fusorSV ouput
starting fusorSV discovery on sample meta_caller_RC1
starting fusorSV discovery on sample meta_caller_RC1_result
finished reading samples in 147.55 sec
cluster merging tool processing samples
completed = True
@ 2022-11-12 08:54:56: Read chain_file:  /usr/local/lib/python2.7/dist-packages/fusorsv/data/liftover/hg19ToHg38.over.chain.gz
@ 2022-11-12 08:54:56: Total entries: 0
@ 2022-11-12 08:54:56: Failed to map: 0
run 0 in 265.02 sec

Here is the vcf file:
##fileformat=VCFv4.2
##fileDate=20221112
##reference=human_g1k_v37_decoy
##FILTER=<ID=LowQual,Description="Low Quality">
##FILTER=<ID=PASS,Description="All filters passed">
##ALT=<ID=INS,Description="Insertion of novel sequence">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=CNV,Description="Copy number variable region">
##ALT=<ID=INV,Description="Inversion">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=CHR2,Number=1,Type=String,Description="Chromosome for END coordinate in case of a translocation">
##INFO=<ID=SVEX,Number=1,Type=Float,Description="Expected Value of the Group SV call given the Prior Targeted Metric Pool">
##INFO=<ID=SEQ_TECH,Number=.,Type=String,Description="Sequencing Technology Used">
##INFO=<ID=TARGET,Number=1,Type=Integer,Description="1 if the call overlaps a target call, 0 otherwise">
##contig=<ID=1,len=249250621>
##contig=<ID=2,len=243199373>
##contig=<ID=3,len=198022430>
##contig=<ID=4,len=191154276>
##contig=<ID=5,len=180915260>
##contig=<ID=6,len=171115067>
##contig=<ID=7,len=159138663>
##contig=<ID=8,len=146364022>
##contig=<ID=9,len=141213431>
##contig=<ID=X,len=155270560>
AND MORE
##INFO=<ID=SVMETHOD,Number=.,Type=String,Description="-1:fusorSV,0:True,1:MetaSV,4:BreakDancer,9:cnMOPS,10:CNVnator,11:Delly,13:GATK,14:GenomeSTRiP,17:Hydra,18:Lumpy,35:BreakSeq,36:Pindel,38:Tigra">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  meta_caller_RC1

Thank you

**Comment by timothyjamesbecker** [comment]
FusorSV needs to have an input folder (the -i argument) that consists of a folder of sample folders (folder of folder of VCF files). Please read the paper or look at the github documentation to see how this works.  In your case it looks like you have a folder called 'meta_caller_RC1' but inside that folder you have a FusorSV input folder and output folder.  You want to change your input path to be pointing to the top directory where the sample folders are it would look like this:

meta_caller_RC1/HG0096 
...
meta_caller_RC1/NA12878

You can check this by simply listing your meta_caller_RC1 folder:

ls -lh /data/meta_caller_RC1

comment back to this discussion with your directory listing for more help!
