### ISSUE TITLE
Caller selection

### ISSUE THREAD

**Issue by lslochov** [timothyjamesbecker/FusorSV#4]
Hi, I'm planning some FusorSV analyses that involve selecting a different set of callers to use compared to the default. I have tried providing a caller exclusion list ("${SVE_HOME}/scripts/FusorSV/data/stage_exclude_list.txt") and modifying the list of default excluded callers in the source code. None of these things appears to affect the output, as FusorSV reports results for the default set of callers every time. What's the proper way to exclude or include new callers in FusorSV's model training?

**Comment by timothyjamesbecker** [comment]
Excluding callers means that you do not want to use those calls in the final fused VCF file.  To do this you invoke the -E flag when you run the command as shown in the newly updated README.md. To not include caller 9 or 10 you would add -E 9,10 to your command line.
