### ISSUE TITLE
FusorSV.py can't find fusorsv.svu_utils

### ISSUE THREAD

**Issue by lslochov** [timothyjamesbecker/FusorSV#5]
FusorSV.py will get to the line "import fusorsv.svu_utils as su" and output "ImportError: No module named fusorsv.svu_utils". I know the svu_utils file is in its proper place, but the main program can't see it for some reason.

**Comment by timothyjamesbecker** [comment]
This looks like an installation error.  Many of the modules like svu_utils, fusion_utils, fusor_utils will function as is, but then you need to update the module paths in the upper import statements.  As a convention almost all imports are at the top with the exception of some of the optional external modules like mygene.  Either use pip or you need to make some changes to the import paths.
