### ISSUE TITLE
FusorSV issue with reading sample VCFs

### ISSUE THREAD

**Issue by lslochov** [timothyjamesbecker/FusorSV#6]
Hi, I've tried FusorSV on the meta_caller_RC1 dataset, and it works great on that, however I've tried using FusorSV on 9 new samples with SVE calls, and the program's output indicates:

"finished reading 0 out of 9 samples generating 0 partitions in 2.36 sec"

I suspect what may be going on is that the import step may be crashing due to misformatted VCF files. Do you have any insight into why this might be the case? FYI these are v4.1 VCF files called on an hg38 reference.

**Comment by lslochov** [comment]
Hi, I figured it out. FusorSV is expecting chromosome names to be [1, 2, 3 ...] but my VCFs were using [chr1, chr2, chr3 ...]

**Comment by timothyjamesbecker** [comment]
As you have figured out, there are some options for unification of chrom
names and they are present at the input when the VCF files are being parsed
and then again when/if you do liftover and produce your final fusorSV VCF
file which will have the S-1.vcf suffix.  If there are any issues that are
reproducible, please open an issue on the github page and I can take a look.

Best,

-Tim
