### ISSUE TITLE
location of the file human_g1k_v37_decoy.bed

### ISSUE THREAD

**Issue by arkyl** [timothyjamesbecker/FusorSV#7]
Hi,
I am testing FusorSV using docker image, and tried to follow the example in the readme. I think I can download the ref fasta human_g1k_v37_decoy.fa from the web, but I had difficulty in finding the file human_g1k_v37_decoy.bed. Is there a way to download it or is it located somewhere in the docker dir structures? Thanks very much.
Yue

**Comment by timothyjamesbecker** [comment]
The svmask file you are looking for is included in the release section
0.1.1 when the command was altered to support arbitrary user-generated BED3
form svmask files:

https://github.com/timothyjamesbecker/FusorSV/releases/download/0.1.1-beta/human_g1k_v37_decoy_exclude.bed

Best,

-Tim
